version: '2'

services:
    web:
      build:
        context: ./
        dockerfile: web.dockerfile
      volumes:
        - ./:/var/www
        - ./vhost.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8888:80"
     
    php:
        # image: php:8.0-fpm
        build: 
          context: ./
          dockerfile: app.dockerfile
        volumes:
          - ./:/var/www
        
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: 'API'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'db' 
            MYSQL_PASSWORD: 'root'
        volumes:
            - ./:/var/www
        ports:
            - 3306:3306
    redis:
        image: "redis:latest"
        hostname: redis
        ports:
          - "6379:6379"